---
apiVersion: v1
kind: Service
metadata:
  name: satisfactory
  labels:
    app: satisfactory
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
# might be necessary for your cluster:
#  loadBalancerIP: <external-IP>
  ports:
    - name: "game"
      port: 7777
      protocol: UDP
      targetPort: 7777
    - name: "gametcp"
      port: 7777
      protocol: TCP
      targetPort: 7777
  selector:
    app: satisfactory
